#! /bin/bash

if ! [[ $(command -v htmlproof) ]]; then
	echo "Installing HTML::Proofer"
	gem install html-proofer -- --use-system-libraries
fi

printf "\nGenerating site...     "
jekyll build -s site -d _site -q
printf "done.\n\n\e[0;36mProofing begins now!\e[0m\n"
htmlproof ./_site
